// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgXnru4F_che-cZSa_qdu2ShdfGZ_xx0',
    appId: '1:439971324656:web:bed2f67d417011b5361835',
    messagingSenderId: '439971324656',
    projectId: 'house-renting-system-test',
    authDomain: 'house-renting-system-test.firebaseapp.com',
    storageBucket: 'house-renting-system-test.appspot.com',
    measurementId: 'G-0XTCT9TS3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZD-Y5QimVspEtp6oeVY8QbPnSH7ejgTU',
    appId: '1:439971324656:android:ad0486038e936fb5361835',
    messagingSenderId: '439971324656',
    projectId: 'house-renting-system-test',
    storageBucket: 'house-renting-system-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACrq-5N1VGGnm3vPlQadc4vBYZKxSKHHw',
    appId: '1:439971324656:ios:8f3f0ce8f56ab67d361835',
    messagingSenderId: '439971324656',
    projectId: 'house-renting-system-test',
    storageBucket: 'house-renting-system-test.appspot.com',
    iosBundleId: 'com.example.hrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACrq-5N1VGGnm3vPlQadc4vBYZKxSKHHw',
    appId: '1:439971324656:ios:a9c6dce23814af8d361835',
    messagingSenderId: '439971324656',
    projectId: 'house-renting-system-test',
    storageBucket: 'house-renting-system-test.appspot.com',
    iosBundleId: 'com.example.hrs.RunnerTests',
  );
}
